# Generated by Django 5.2.6 on 2025-09-20 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('role', models.CharField(choices=[('delivery', 'Delivery'), ('kitchen', 'Kitchen')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffDailyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_hours', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_daily_hours',
                'unique_together': {('staff', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('work_minutes', models.IntegerField(blank=True, editable=False, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_shifts',
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='ck_shift_time_order'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('staff',), name='ux_staff_one_open_shift')],
            },
        ),
    ]
