# Generated by Django 5.2.6 on 2025-10-15 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_align_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffshift',
            name='ck_shift_time_order',
        ),
        migrations.RemoveConstraint(
            model_name='staffshift',
            name='ux_staff_one_open_shift',
        ),
        migrations.RenameIndex(
            model_name='staff',
            new_name='staff_role_3ed139_idx',
            old_name='idx_staff_role_active',
        ),
        migrations.AddField(
            model_name='staffshift',
            name='client_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='display_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^010-\\d{4}-\\d{4}$', '010-1234-5678 형태여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('MANAGER', 'MANAGER'), ('KITCHEN', 'KITCHEN'), ('DELIVERY', 'DELIVERY')], max_length=16),
        ),
        migrations.AlterField(
            model_name='staffshift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='staffdailyhours',
            index=models.Index(fields=['work_date'], name='staff_daily_work_da_ef1a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='staffshift',
            index=models.Index(fields=['staff', 'started_at'], name='staff_shift_staff_i_085937_idx'),
        ),
        migrations.AddIndex(
            model_name='staffshift',
            index=models.Index(fields=['ended_at'], name='staff_shift_ended_a_90eecb_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffshift',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('staff',), name='uniq_active_shift_per_staff'),
        ),
    ]
