# Generated by Django 5.2.6 on 2025-10-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffdailyhours',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffdailyhours',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffshift',
            name='staff',
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='staff_role_3ed139_idx',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('KITCHEN', 'Kitchen'), ('DELIVERY', 'Delivery')], default='DELIVERY', max_length=16),
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff_staff',
        ),
        migrations.DeleteModel(
            name='StaffDailyHours',
        ),
        migrations.DeleteModel(
            name='StaffShift',
        ),
    ]
