# Generated by Django 5.2.6 on 2025-09-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('out_for_delivery', 'OutForDelivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('order_source', models.CharField(choices=[('GUI', 'GUI'), ('VOICE', 'VOICE')], default='GUI', max_length=10)),
                ('receiver_name', models.TextField(blank=True, null=True)),
                ('receiver_phone', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_label', models.TextField(blank=True, null=True)),
                ('address_meta', models.JSONField(blank=True, null=True)),
                ('payment_token', models.TextField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='accounts.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDinner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_label', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('base_price_cents', models.PositiveIntegerField()),
                ('style_adjust_cents', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dinner_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.dinnertype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinners', to='orders.order')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.servingstyle')),
            ],
            options={
                'db_table': 'order_dinner',
            },
        ),
        migrations.CreateModel(
            name='OrderDinnerItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('final_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('change_type', models.CharField(choices=[('unchanged', 'Unchanged'), ('added', 'Added'), ('removed', 'Removed'), ('increased', 'Increased'), ('decreased', 'Decreased')], default='unchanged', max_length=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.menuitem')),
                ('order_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderdinner')),
            ],
            options={
                'db_table': 'order_dinner_item',
            },
        ),
        migrations.CreateModel(
            name='OrderDinnerOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_group_name', models.TextField()),
                ('option_name', models.TextField()),
                ('price_delta_cents', models.PositiveIntegerField(default=0)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('order_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.orderdinner')),
            ],
            options={
                'db_table': 'order_dinner_option',
            },
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_group_name', models.TextField()),
                ('option_name', models.TextField()),
                ('price_delta_cents', models.PositiveIntegerField(default=0)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('order_dinner_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.orderdinneritem')),
            ],
            options={
                'db_table': 'order_item_option',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-ordered_at'], name='idx_orders_customer_recent'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdinneritem',
            unique_together={('order_dinner', 'item')},
        ),
    ]
