# Generated by Django 5.2.6 on 2025-09-19 08:24

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.CharField(max_length=64)),
                ('real_name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='phone number format: 010-0000-0000', regex='^010-\\d{4}-\\d{4}$')])),
                ('addresses', models.JSONField(default=list)),
                ('loyalty_tier', models.TextField(choices=[('none', 'None'), ('silver', 'Silver'), ('gold', 'Gold')], default='none')),
                ('profile_consent', models.BooleanField(default=False)),
                ('profile_consent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
                'constraints': [models.CheckConstraint(condition=models.ExpressionWrapper(django.db.models.expressions.RawSQL("jsonb_typeof(addresses) = 'array' AND jsonb_array_length(addresses) <= 3", []), output_field=models.BooleanField()), name='ck_customer_addresses_json'), models.CheckConstraint(condition=models.Q(('loyalty_tier__in', ['none', 'silver', 'gold'])), name='ck_customer_loyalty_tier')],
            },
        ),
    ]
