# Generated by Django 5.2.6 on 2025-10-15 04:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_orders_notify_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'FixedAmount')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('min_subtotal_cents', models.IntegerField(blank=True, null=True)),
                ('max_discount_cents', models.IntegerField(blank=True, null=True)),
                ('stackable_with_membership', models.BooleanField(default=True)),
                ('stackable_with_coupons', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('ANY', 'Any'), ('GUI', 'GUI'), ('VOICE', 'VOICE')], default='ANY', max_length=8)),
                ('max_redemptions_global', models.IntegerField(blank=True, null=True)),
                ('max_redemptions_per_user', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotion_coupon',
                'indexes': [models.Index(fields=['active', 'valid_from', 'valid_until'], name='promotion_c_active_54dcbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Membership', max_length=120)),
                ('percent_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='accounts.customer')),
            ],
            options={
                'db_table': 'promotion_membership',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField(default=0)),
                ('channel', models.CharField(default='GUI', max_length=8)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotion.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='orders.order')),
            ],
            options={
                'db_table': 'promotion_coupon_redemption',
                'indexes': [models.Index(fields=['coupon', 'customer'], name='promotion_c_coupon__8aaa8e_idx'), models.Index(fields=['coupon', 'redeemed_at'], name='promotion_c_coupon__be434a_idx')],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'order'), name='uq_coupon_order_once')],
            },
        ),
    ]
